### PR TITLE
Set up JUnit4 Test (updated)

### PR DESCRIPTION
**Pull request by Korkianer**
@nicolaiparlog  #pray

### CODE REVIEW

**Comment by NikMass** [comment]
🙏

**Comment by nipafx** [comment]
"this has to work now!" is somewhat funny but I need a little more information. Please give the PR an expressive title and a short description linking to the issue, so I know what I'm looking at.

**Comment by nipafx** [comment]
PS: I don't get notifications for edits, so leave a comment once you're done.

**Comment by Korkianer** [comment]
@nicolaiparlog 
sorry for the wrong Title. Issue #11 is hopefully solved with this request 😄 
I changed the package and also the fun like you commented.

**Comment by nipafx** [comment]
I'm a little confused why you started a new pull request for this - you should have continued your work in #25. Also, you forgot to branch before coding, which will cause problems when you pull the newest changes from the merged `master`.

Other than that, the PR can be merged. :+1:

**Pull request merged**
