### PR TITLE
Readme for version 2.0

### PR DESCRIPTION
**Pull request by NikMass**
@nicolaiparlog 
Changed the explanation of "launching the application"
The Readme is now ready for version 2 release
Issue #31

### CODE REVIEW

**Review by nipafx — CHANGES_REQUESTED** [review]
Code schreibt man typischerweise so:

    ```
    java -jar target/Th-Bingen-2.0-SNAPSHOT-jar-with-dependencies.jar
    ```

**Comment by NikMass** [comment]
@nicolaiparlog 
i changed it, hope its ok now 😃

**Review by nipafx — APPROVED** [review]

**Comment by nipafx** [comment]
:+1:

**Comment by nipafx** [comment]
Sollte der nicht gemergt werden?

**Pull request merged**
