### PR TITLE
HelloWorld.kt/pom.xml

### PR DESCRIPTION
**Pull request by MarcoChrist**
@nicolaiparlog 
Dont know if this is correct (issue #8)

### CODE REVIEW

**Comment by nipafx** [comment]
:bulb: Please use a fork to work on feature branches. Otherwise this repo gets filled up with [lots of branches](https://github.com/SJ1337/Th-Bingen/branches).

**Comment by nipafx** [comment]
This doesn't work yet. You can try that out yourself by running `mvn clean install` in the project's root folder. You will get an error complaining that there's no POM. Even if you move the POM into the correct place, no sources will get compiled. Have a closer look at the Energy Model's directory layout.

**Comment by MarcoChrist** [comment]
@nicolaiparlog 
I updated the pom.xml. mvn clean install works fine without errors, but i cant execute the java -jar command.

**Comment by SJ1337** [comment]
test file has been added (junit)

**Comment by nipafx** [comment]
> mvn clean install works fine without errors

Only if you run it in the `src` directory, which is _not_ the root directory. Also, have a look at the message block, the compiler creates. It says that it didn't compile any sources. No compilation ~> no class files in the JAR ~> nothing to execute.

**Comment by Korkianer** [comment]
Now closing this request to build a new one

**Pull request closed without merging**
