### PR TITLE
JUnit4

### PR DESCRIPTION
**Pull request by Korkianer**
(#11) I updated the pom, "mvn clean test" works. @nikolaiparlog

### CODE REVIEW

**Comment by nipafx** [comment]
You have created a new POM and an in fact an entire new project tree in the folder `TH-Bingen`. You should instead extend the existing POM and add the tests to the existing `src` folder.

**Comment by Korkianer** [comment]
ah ok, so i just have to edit the existing version?

**Comment by nipafx** [comment]
Sure, remember the goal is to have a single project that we extend over time. Creating a new project on each issue would be somewhat counterproductive. :wink:

**Comment by Korkianer** [comment]
the new pull request is better :-)

**Comment by nipafx** [comment]
Yes, you can close this one.

**Pull request closed without merging**
